app/models.py
from . import db
from random import randrange

#Modelo de base de datos del producto
class Producto(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    codigo = db.Column(db.String(10), nullable=False)
    descripcion = db.Column(db.String(80), nullable=False)
    categoria = db.Column(db.String(10), nullable=False)
    stock = db.Column(db.Integer, nullable=False)
    bodega = db.Column(db.Integer, nullable=False)
    precio = db.Column(db.Float, nullable=False)
    iva = db.Column(db.Float, nullable=False)
    precioTotal= db.Column(db.Float, nullable=False)

    def __repr__(self):
        return f"Producto('{self.codigo}', '{self.descripcion}', '{self.categoria}', '{self.stock}', '{self.bodega}', '{self.precio}', '{self.iva}', '{self.precioTotal}')"

#Modelo de base de datos de la categoria
class Categoria(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    codcate = db.Column(db.Integer, nullable=False)
    nomcate = db.Column(db.String(20), nullable=False)
    tipocate = db.Column(db.String(20), nullable=False)

    def __repr__(self):
        return f"Categoria('{self.codcate}', '{self.nomcate}', '{self.tipocate}')"

    def generar_codigo(self, numero):
        return randrange(100, 6000)

app/index/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, FloatField, validators, ValidationError, SubmitField
from wtforms.validators import DataRequired, Length
from ..models import *
from re import match, findall

#Formulario del producto
class registrarForm(FlaskForm):
    codigo = StringField('Codigo del producto', validators=[DataRequired("Este campo es obligatorio"),
                                                            Length(min=5, max=5, message="El codigo debe contener 5 caracteres")])
    descripcion = StringField('Nombre del producto', validators=[DataRequired("Este campo es obligatorio")])
    categoria = StringField('Nombre de la categoria', validators=[DataRequired("Este campo es obligatorio")])
    stock = IntegerField('Cantidad del producto en stock', validators=[DataRequired("Este campo es obligatorio")])
    bodega = IntegerField('Numero de bodega', validators=[DataRequired("Este campo es obligatorio")])
    precio = FloatField('Precio del producto', validators=[DataRequired("Este campo es obligatorio")])
    iva = FloatField('Iva del producto', validators=[DataRequired("Este campo es obligatorio")])
    submit = SubmitField('Registrar')

    #Validacion del iva
    def vaidate_iva(self, iva):
        if iva.data <= 0:
            raise ValidationError("Valor de iva incorrecto")

    #Validacion del codigo un caracter y cuatro numeros consecutivos
    def validate_letter(self, codigo):
        if not match(r'\D?', codigo.data):
            raise ValidationError('El codigo debe empezar con una letra')
        elif len(findall(r'\D', codigo.data)) > 1:
            raise ValidationError('Los numeros no son consecutivos')

#Formulario de la categoria
class registrarcatForm(FlaskForm):
    cod_cate = IntegerField('Codigo de la categoria (entre 100 a 6000)', validators=[DataRequired("Este campo es obligatorio"),
                                                        Length(min=100, max=6000, message="El codigo debe estar en un rango entre 100 a 600")])
    nom_cate = StringField('Nombre de la categoria', validators=[DataRequired("Este campo es obligatorio")])
    tipo_cate = StringField('Tipo de categoria', validators=[DataRequired("Este campo es obligatorio")])
    submit = SubmitField('Registrar')

app/__init__.py
from flask import Flask
from .Config import Config
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)

    from .index.routes import index
    app.register_blueprint(index)

    return app

app/index/routes.py
from flask import render_template, url_for, redirect, request, Blueprint
from .. import db
from ..models import *
from .forms import *

index = Blueprint("index", __name__)

#Pagina de inicio
@index.route("/")
@index.route("/home")
def home():
    form = registrarForm()
    return render_template('menu.html', form=form, title="Registrar producto")

#Metodo para ingresar producto
@index.route("/insert", methods=["GET", "POST"])
def insert():
    form = registrarForm()
    if form.validate_on_submit():
        producto = Producto(codigo=form.codigo.data,
                            descripcion=form.descripcion.data,
                            categoria=form.categoria.data,
                            stock=form.stock.data,
                            bodega=form.bodega.data,
                            precio=form.precio.data,
                            iva=((form.iva.data/100)+1),
                            precioTotal=((form.precio.data) + ((form.iva.data/100)+1))) #Formula para mostrar el precio total
        db.session.add(producto)
        db.session.commit()
        return redirect(url_for('index.home'))
    return render_template('insert.html', form=form)

#Metodo para ingresar categoria
@index.route("/insertcat", methods=["GET", "POST"])
def insertcat():
    form = registrarcatForm()
    if form.validate_on_submit():
        categoria = Categoria(cod_cate=form.cod_cate.data,
                              nom_cate=form.nom_cate.data,
                              tipo_cate=tipo_cat(form.cod_cate.data))
        db.session.add(categoria)
        db.session.commit()
        return redirect(url_for('index.home'))
    return render_template('insertcat.html', form=form)

#Metodo para mostrar productos
@index.route("/tablaprod")
def tablaprod():
    productos = db.session.query(Producto).all()
    return render_template('tablaprod.html', productos=productos)

#Metodo para mostrar categorias
@index.route("/tablacat")
def tablacat():
    categorias = db.session.query(Categoria).all()
    return render_template('tablacat.html', categorias=categorias)

#Validacion del tipo de categoria
def tipo_cat(numero):
    if numero in range(100, 1500):
        return 'PERSONAL'
    elif numero in range(1501, 3000):
        return 'ANIMAL'
    elif numero in range(3001, 6000):
        return 'HOGAR-FERRETERIA'

app/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <title>Empresa</title>
</head>
<body>
    <main role="main" class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }} mt-3">
                        {{ message }}
                        <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        
        {% block content %}
        {% endblock content%}
    </main>

    <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script> 
</body>
</html>

app/templates/insert.html
{% extends "home.html" %}

{% block content %}
<section class="row mt-2">
    <div class="col-lg-6 offset-3">
        
        <form class="card bg-dark border-dark mt-5" action="{{ url_for('index.insert') }}" method="POST">
          <div class="row">
            <div class="text-center h1 text-white p-2 col-lg-12">Registrar producto</div>
              
              <div class="text-center form-group col-lg-10 offset-1">
                {{ form.codigo.label(class="form-control-label fst-italic text-light pt-3") }}
                {{ form.codigo(class="form-control mt-2") }}
              </div>
              <div class="text-center form-group col-lg-10 offset-1">
                {{ form.descripcion.label(class="form-control-label fst-italic text-light pt-3") }}
                {{ form.descripcion(class="form-control mt-2") }}
              </div>
              <div class="text-center form-group col-lg-10 offset-1">
                {{ form.categoria.label(class="form-control-label fst-italic text-light pt-3") }}
                {{ form.categoria(class="form-control mt-2") }}
              </div>
              <div class="text-center form-group col-lg-10 offset-1">
                {{ form.stock.label(class="form-control-label fst-italic text-light pt-3") }}
                {{ form.stock(class="form-control mt-2") }}
              </div>
              <div class="text-center form-group col-lg-10 offset-1">
                {{ form.bodega.label(class="form-control-label fst-italic text-light pt-3") }}
                {{ form.bodega(class="form-control mt-2") }}
              </div>
              <div class="text-center form-group col-lg-10 offset-1">
                {{ form.precio.label(class="form-control-label fst-italic text-light pt-3") }}
                {{ form.precio(class="form-control mt-2") }}
              </div>
              <div class="text-center form-group col-lg-10 offset-1">
                {{ form.iva.label(class="form-control-label fst-italic text-light pt-3") }}
                {{ form.iva(class="form-control mt-2") }}
              </div>    
          </div>
          <div class="text-center">
            {{ form.submit(class="btn btn-danger mt-4")}}
          </div>
        </form>
        </div>
</section>

{% endblock content %}

app/templates/insertcat.html
{% extends "home.html" %}

{% block content %}
<section class="row mt-2">
    <div class="col-lg-6 offset-3">
        
        <form class="card bg-dark border-dark mt-5" action="{{ url_for('index.insertcat') }}" method="POST">
          <div class="row">
            <div class="text-center h1 text-white p-2 col-lg-12">Registrar categoria</div>
              
              <div class="text-center form-group col-lg-10 offset-1">
                {{ form.cod_cate.label(class="form-control-label fst-italic text-light pt-3") }}
                {{ form.cod_cate(class="form-control mt-2") }}
              </div>
              <div class="text-center form-group col-lg-10 offset-1">
                {{ form.nom_cate.label(class="form-control-label fst-italic text-light pt-3") }}
                {{ form.nom_cate(class="form-control mt-2") }}
              </div>
              <div class="text-center form-group col-lg-10 offset-1">
                {{ form.tipo_cate.label(class="form-control-label fst-italic text-light pt-3") }}
                {{ form.tipo_cate(class="form-control mt-2") }}
              </div>
          </div>
          <div class="text-center">
            {{ form.submit(class="btn btn-danger mt-4")}}
          </div>
        </form>
        </div>

{% endblock content %}

app/templates/menu.html
{% extends "home.html" %}

{% block content %}
<section class="row mt-5">
    <div class="col-lg-6 offset-3">
        <div class="card bg-dark border-danger mt-5">
            <h3 class="card-title fw-bold text-light text-center my-2">Elegir una Opcion</h3>
            <ul class="list-group list-group-flush">
                <li class="list-group-item bg-dark text-light border-danger">
                    <span class="fst-italic fs-5">Agregar producto</span>
                    <a href="{{ url_for('index.insert') }}" class="btn btn-danger float-end">Registrar</a>
                </li>
                <li class="list-group-item bg-dark text-light border-danger">
                    <span class="fst-italic fs-5">Agregar categoria</span>
                    <a href="{{ url_for('index.insertcat') }}" class="btn btn-danger float-end">Registrar</a>
                </li>
                <li class="list-group-item bg-dark text-light border-danger">
                    <span class="fst-italic fs-5">Mostrar producto</span>
                    <a href="{{ url_for('index.tablaprod') }}" class="btn btn-danger float-end">Mostrar</a>
                </li>
                <li class="list-group-item bg-dark text-light border-danger">
                    <span class="fst-italic fs-5">Mostar categoria</span>
                    <a href="{{ url_for('index.tablacat') }}" class="btn btn-danger float-end">Mostrar</a>
                </li>
                </ul>
        </div>
    </div>
</section>
{% endblock content %}

app/templates/tablacat.html
{% extends "home.html" %}

{% block content %}
<section class="mt-3">
    <table class="table table-dark table-hover">
        <thead>
            <tr>
                <th>Codigo de categoria</th>
                <th>Nombre</th>
                <th>Tipo</th>
            </tr>
        </thead>
        <tbody>
            {% for categoria in categorias %}
                <tr>
                    <td>{{ producto.codigo }}</td>
                    <td>{{ producto.descripcion }}</td>
                    <td>{{ producto.categoria }}</td>
                    <td>{{ producto.stock }}</td>  
                    <td>{{ producto.bodega }}</td>
                    <td>{{ producto.precio }}</td>
                    <td>{{ producto.iva }}</td>                                           
                </tr>
            {% endfor %}
        </tbody>
    </table>
</section>
{% endblock content %}

app/templates/tablaprod.html
{% extends "home.html" %}

{% block content %}
<section class="mt-3">
    <table class="table table-dark table-hover">
        <thead>
            <tr>
                <th>Codigo</th>
                <th>Descripcion</th>
                <th>Categoria</th>
                <th>Stock</th>
                <th>Bodega</th>
                <th>Precio</th>
                <th>Iva</th>
            </tr>
        </thead>
        <tbody>
            {% for producto in productos %}
                <tr>
                    <td>{{ producto.codigo }}</td>
                    <td>{{ producto.descripcion }}</td>
                    <td>{{ producto.categoria }}</td>
                    <td>{{ producto.stock }}</td>  
                    <td>{{ producto.bodega }}</td>
                    <td>{{ producto.precio }}</td>
                    <td>{{ producto.iva }}</td>                                           
                </tr>
            {% endfor %}
        </tbody>
    </table>
</section>
{% endblock content %}